apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mavendeployment
  labels:
    app: mavenapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      labels:
        app: mavenapp
    spec:
      containers:
      - name: mavenappcontainer
        image: 015901552966.dkr.ecr.ap-south-1.amazonaws.com/maven-web-app:${build_Number}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 40
          httpGet:
            path: /maven-web-application
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30




---

apiVersion: v1
kind: Service
metadata: 
  name: mavensvc
spec:
  type: ClusterIP
  selector:
    app: mavenapp
  ports:
  - port: 80
    targetPort: 8080
    
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mavenapphpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: mavendeployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
      
    
