apiVersion: v1 
kind: Pod 
metadata:
  name: mavenpod
  labels:
    app: mavenapp
spec:
  containers:
  - name: mavenappcontainer
    image: 015901552966.dkr.ecr.ap-south-1.amazonaws.com/maven-web-app:${build_Number}
    resources:
      requests:
        cpu: "300m"
        memory: "300Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"  
    ports:
    - containerPort: 8080
    


---

apiVersion: v1 
kind: Service 
metadata:
  name: mavenappsvc
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
  - port: 80
    targetPort: 8080
    
